version: 1
disable_existing_loggers: true
formatters:
  standard:
    datefmt: '%Y-%m-%d %H:%M:%S'
    format: '[%(asctime)s] %(name)4s | %(levelname)-7s | %(message)s -- @%(filename)s:%(lineno)d %(funcName)s()'
  chat:
    datefmt: '%H:%M:%S'
    format: "[%(asctime)s] %(levelname)-7s | %(message)s\n           at %(filename)s:%(lineno)d, %(funcName)s()"
handlers:
  telegram:
    level: DEBUG
    formatter: chat
    class: busm.BusmHandler
    subject: 'My Background Task'
    config: ~/tg-config.yaml
  line:
    level: DEBUG
    formatter: chat
    class: busm.BusmHandler
    channel: line
    subject: 'My Background Task'
    config: ~/line-config.yaml
  console:
    level: DEBUG
    formatter: standard
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  busm:
    level: DEBUG
    handlers:
      - telegram
      - line
      - console
    propagate: yes
